language: node_js
dist: focal
node_js:
  - '18'
script:
  - npm run lint
  - npm run build
cache:
  directories:
    - node_modules
    - website/node_modules
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install faraday-net_http -v '3.3.0' # Fix faraday version
  - gem install logger
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: website/build/messenger-style
    target-branch: gh-pages
    on:
      branch: master
