language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm run build
cache:
  directories:
    - node_modules
    - website/node_modules
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: website/build/messenger-style
    target-branch: gh-pages
    on:
      branch: master
